import {
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  Briefcase,
  Building2,
  Calculator,
  Check,
  Clock,
  Code2,
  Fingerprint,
  GraduationCap,
  Handshake,
  HardHat,
  Megaphone,
  MessageCircleQuestion,
  Radar,
  Send,
  Shield,
  SlidersHorizontal,
  Sprout,
  Stethoscope,
  Truck,
  Users,
  Utensils,
  Zap,
} from "lucide-react"

const DEFAULT_FILIERE_THEME = {
  icon: Briefcase,
  hue: "blue",
  bar: "bg-blue-400",
  tile: "bg-blue-500/10 text-blue-600 group-hover:bg-blue-600 group-hover:text-white",
  hover: "hover:border-blue-600/70",
}

const FILIERE_THEME = {
  "tech-dev": {
    icon: Code2,
    hue: "sky",
    bar: "bg-sky-400",
    tile: "bg-sky-500/10 text-sky-600 group-hover:bg-sky-600 group-hover:text-white",
    hover: "hover:border-sky-600/70",
  },
  "marketing-com": {
    icon: Megaphone,
    hue: "fuchsia",
    bar: "bg-fuchsia-400",
    tile: "bg-fuchsia-500/10 text-fuchsia-600 group-hover:bg-fuchsia-600 group-hover:text-white",
    hover: "hover:border-fuchsia-600/70",
  },
  "commercial-vente": {
    icon: Handshake,
    hue: "orange",
    bar: "bg-orange-400",
    tile: "bg-orange-500/10 text-orange-600 group-hover:bg-orange-600 group-hover:text-white",
    hover: "hover:border-orange-600/70",
  },
  "comptabilite-finance": {
    icon: Calculator,
    hue: "emerald",
    bar: "bg-emerald-400",
    tile: "bg-emerald-500/10 text-emerald-600 group-hover:bg-emerald-600 group-hover:text-white",
    hover: "hover:border-emerald-600/70",
  },
  "ressources-humaines": {
    icon: Users,
    hue: "violet",
    bar: "bg-violet-400",
    tile: "bg-violet-500/10 text-violet-600 group-hover:bg-violet-600 group-hover:text-white",
    hover: "hover:border-violet-600/70",
  },
  "btp-genie-civil": {
    icon: HardHat,
    hue: "amber",
    bar: "bg-amber-400",
    tile: "bg-amber-500/10 text-amber-600 group-hover:bg-amber-600 group-hover:text-white",
    hover: "hover:border-amber-600/70",
  },
  "logistique-transport": {
    icon: Truck,
    hue: "cyan",
    bar: "bg-cyan-400",
    tile: "bg-cyan-500/10 text-cyan-600 group-hover:bg-cyan-600 group-hover:text-white",
    hover: "hover:border-cyan-600/70",
  },
  "sante-medical": {
    icon: Stethoscope,
    hue: "rose",
    bar: "bg-rose-400",
    tile: "bg-rose-500/10 text-rose-600 group-hover:bg-rose-600 group-hover:text-white",
    hover: "hover:border-rose-600/70",
  },
  administration: {
    icon: Building2,
    hue: "blue",
    bar: "bg-blue-400",
    tile: "bg-blue-500/10 text-blue-600 group-hover:bg-blue-600 group-hover:text-white",
    hover: "hover:border-blue-600/70",
  },
  "education-formation": {
    icon: GraduationCap,
    hue: "indigo",
    bar: "bg-indigo-400",
    tile: "bg-indigo-500/10 text-indigo-600 group-hover:bg-indigo-600 group-hover:text-white",
    hover: "hover:border-indigo-600/70",
  },
  "hotellerie-restauration": {
    icon: Utensils,
    hue: "teal",
    bar: "bg-teal-400",
    tile: "bg-teal-500/10 text-teal-600 group-hover:bg-teal-600 group-hover:text-white",
    hover: "hover:border-teal-600/70",
  },
  "agriculture-agrobusiness": {
    icon: Sprout,
    hue: "lime",
    bar: "bg-lime-400",
    tile: "bg-lime-500/10 text-lime-600 group-hover:bg-lime-600 group-hover:text-white",
    hover: "hover:border-lime-600/70",
  },
  "securite-gardiennage": {
    icon: Shield,
    hue: "red",
    bar: "bg-red-400",
    tile: "bg-red-500/10 text-red-600 group-hover:bg-red-600 group-hover:text-white",
    hover: "hover:border-red-600/70",
  },
}

const getFiliereTheme = (code) => FILIERE_THEME[code] ?? DEFAULT_FILIERE_THEME

export default getFiliereTheme