/**
 * Données de démonstration et fallback pour l'espace administration JobAlert CI.
 * Utilisées automatiquement si le backend FastAPI n'est pas encore démarré ou connecté.
 */

export const INITIAL_ADMINS = [
  {
    id: "adm-1",
    full_name: "Koffi Admin Principal",
    email: "admin@jobalert.ci",
    role: "super_admin",
    is_active: true,
    created_at: "2026-01-15T08:00:00Z",
    last_login_at: new Date().toISOString(),
    permissions: [
      "manage_offers",
      "manage_sources",
      "manage_filieres",
      "trigger_scrape",
      "manage_logs",
      "manage_users",
    ],
  },
  {
    id: "adm-2",
    full_name: "Awa Superviseur",
    email: "awa.superviseur@jobalert.ci",
    role: "superviseur",
    is_active: true,
    created_at: "2026-02-10T09:30:00Z",
    last_login_at: "2026-08-20T11:15:00Z",
    permissions: [
      "manage_offers",
      "manage_sources",
      "trigger_scrape",
      "manage_logs",
    ],
  },
  {
    id: "adm-3",
    full_name: "Marc Modérateur",
    email: "marc.moderateur@jobalert.ci",
    role: "moderateur",
    is_active: false,
    created_at: "2026-03-01T14:20:00Z",
    last_login_at: "2026-07-12T16:45:00Z",
    permissions: [
      "manage_offers",
      "manage_logs",
    ],
  },
]

export const INITIAL_SUBSCRIBERS = [
  {
    id: "sub-1",
    email: "jean.kouassi@gmail.com",
    full_name: "Jean Kouassi",
    status: "active",
    subscribed_at: "2026-06-10T10:14:00Z",
    filieres: ["Tech & Dev", "Marketing & Com"],
    daily_count: 18,
  },
  {
    id: "sub-2",
    email: "fatou.traore@yahoo.fr",
    full_name: "Fatou Traoré",
    status: "active",
    subscribed_at: "2026-07-01T12:00:00Z",
    filieres: ["Comptabilité & Finance", "RH"],
    daily_count: 12,
  },
  {
    id: "sub-3",
    email: "emmanuel.bamba@outlook.com",
    full_name: "Emmanuel Bamba",
    status: "paused",
    subscribed_at: "2026-05-18T08:30:00Z",
    filieres: ["BTP & Génie Civil"],
    daily_count: 5,
  },
  {
    id: "sub-4",
    email: "sarah.k@gmail.com",
    full_name: "Sarah Koné",
    status: "active",
    subscribed_at: "2026-08-01T07:45:00Z",
    filieres: ["Santé & Médical", "Administration"],
    daily_count: 9,
  },
  {
    id: "sub-5",
    email: "yves.diop@free.fr",
    full_name: "Yves Diop",
    status: "unsubscribed",
    subscribed_at: "2026-04-11T16:20:00Z",
    filieres: ["Logistique & Transport"],
    daily_count: 0,
  },
  {
    id: "sub-6",
    email: "clarisse.yao@gmail.com",
    full_name: "Clarisse Yao",
    status: "active",
    subscribed_at: "2026-08-15T09:10:00Z",
    filieres: ["Tech & Dev", "Commercial & Vente"],
    daily_count: 14,
  },
]

export const INITIAL_SCRAPERS = [
  {
    id: "src-novojob",
    code: "novojob",
    name: "Novojob CI",
    status: "active",
    schedule_cron: "0 6 * * *",
    schedule_label: "Tous les matins à 06:00",
    interval_minutes: 1440,
    last_run_at: "2026-08-22T06:02:15Z",
    last_status: "success",
    last_duration_ms: 12400,
    last_error: null,
    total_runs: 184,
    offers_found_last: 28,
  },
  {
    id: "src-linkedin",
    code: "linkedin",
    name: "LinkedIn Jobs CI",
    status: "active",
    schedule_cron: "15 6 * * *",
    schedule_label: "Tous les matins à 06:15",
    interval_minutes: 1440,
    last_run_at: "2026-08-22T06:15:40Z",
    last_status: "success",
    last_duration_ms: 18200,
    last_error: null,
    total_runs: 184,
    offers_found_last: 42,
  },
  {
    id: "src-emploidakar",
    code: "emploidakar",
    name: "EmploiDakar CI",
    status: "active",
    schedule_cron: "30 6 * * *",
    schedule_label: "Tous les matins à 06:30",
    interval_minutes: 1440,
    last_run_at: "2026-08-22T06:30:10Z",
    last_status: "success",
    last_duration_ms: 9800,
    last_error: null,
    total_runs: 182,
    offers_found_last: 15,
  },
  {
    id: "src-goafrica",
    code: "goafrica",
    name: "Go Africa Online",
    status: "active",
    schedule_cron: "45 6 * * *",
    schedule_label: "Tous les matins à 06:45",
    interval_minutes: 1440,
    last_run_at: "2026-08-22T06:45:22Z",
    last_status: "partial_failure",
    last_duration_ms: 24500,
    last_error: "Timeout sur la page 4 des résultats (reconnexion automatique réussie)",
    total_runs: 180,
    offers_found_last: 19,
  },
]

export const INITIAL_SCRAPE_RUNS = [
  {
    id: "run-20260822-1",
    run_date: "2026-08-22",
    status: "success",
    started_at: "2026-08-22T06:00:00Z",
    completed_at: "2026-08-22T06:46:00Z",
    duration_ms: 46000,
    triggered_by: "system:cron",
    total_offers_scraped: 104,
    new_offers_inserted: 74,
    duplicates_filtered: 30,
    notes: "Collecte matinale standard",
  },
  {
    id: "run-20260821-1",
    run_date: "2026-08-21",
    status: "success",
    started_at: "2026-08-21T06:00:00Z",
    completed_at: "2026-08-21T06:44:10Z",
    duration_ms: 44100,
    triggered_by: "system:cron",
    total_offers_scraped: 98,
    new_offers_inserted: 65,
    duplicates_filtered: 33,
    notes: "Collecte matinale standard",
  },
  {
    id: "run-20260820-2",
    run_date: "2026-08-20",
    status: "success",
    started_at: "2026-08-20T14:30:00Z",
    completed_at: "2026-08-20T14:38:00Z",
    duration_ms: 18000,
    triggered_by: "admin:adm-1",
    total_offers_scraped: 24,
    new_offers_inserted: 12,
    duplicates_filtered: 12,
    notes: "Rattrapage manuel LinkedIn",
  },
]

export const INITIAL_LOGS = [
  {
    id: "log-1",
    created_at: "2026-08-22T08:00:05Z",
    module: "envoi",
    type: "audit",
    niveau: "info",
    action: "envoi",
    admin_name: "Automate Système",
    target_table: "email_digests",
    message: "Envoi du digest quotidien réussi : 10,550 emails distribués à 8h00.",
    details: { total_emails: 10550, success: 10542, bounce: 8 },
  },
  {
    id: "log-2",
    created_at: "2026-08-22T06:45:22Z",
    module: "scraping",
    type: "technique",
    niveau: "warning",
    action: "scraping",
    admin_name: "Automate Système",
    target_table: "source_scrape_runs",
    message: "Go Africa Online : ralentissement réseau détecté sur la page 4, reprise automatique effectuée.",
    details: { source: "goafrica", duration_ms: 24500, retry_count: 2 },
  },
  {
    id: "log-3",
    created_at: "2026-08-22T06:15:40Z",
    module: "scraping",
    type: "technique",
    niveau: "info",
    action: "scraping",
    admin_name: "Automate Système",
    target_table: "job_offers",
    message: "LinkedIn CI : 42 offres collectées, 29 nouvelles insérées, 13 doublons écartés.",
    details: { inserted: 29, duplicates: 13, source: "linkedin" },
  },
  {
    id: "log-4",
    created_at: "2026-08-21T18:30:12Z",
    module: "admin",
    type: "audit",
    niveau: "info",
    action: "modification",
    admin_name: "Koffi Admin Principal",
    target_table: "administrators",
    message: "Mise à jour des permissions du compte 'Awa Superviseur'.",
    details: { target_id: "adm-2", updated_permissions: ["manage_offers", "manage_sources", "trigger_scrape", "manage_logs"] },
  },
  {
    id: "log-5",
    created_at: "2026-08-21T11:20:00Z",
    module: "offres",
    type: "audit",
    niveau: "warning",
    action: "suppression",
    admin_name: "Awa Superviseur",
    target_table: "job_offers",
    message: "Désactivation de l'offre 'Développeur Python Senior' (marquée comme pourvue).",
    details: { offer_id: "off-102", reason: "Annonce expirée côté recruteur" },
  },
  {
    id: "log-6",
    created_at: "2026-08-20T09:14:22Z",
    module: "scraping",
    type: "technique",
    niveau: "error",
    action: "scraping",
    admin_name: "Automate Système",
    target_table: "source_scrape_runs",
    message: "Erreur de parsing structurel sur 2 offres Novojob (structure HTML modifiée).",
    details: { error: "Selector '.salary-badge' not found", affected_urls: ["https://novojob.com/ci/offer-8891"] },
  },
]

export const INITIAL_OFFERS = [
  {
    id: "off-1",
    title: "Lead Developer Fullstack React & Node.js",
    company: "Orange Côte d'Ivoire",
    location: "Abidjan, Cocody",
    filiere: "Tech & Dev",
    source: "LinkedIn",
    contract_type: "CDI",
    status: "active",
    visible_site: true,
    created_at: "2026-08-22T06:12:00Z",
    source_url: "https://linkedin.com/jobs/view/123456",
    salary_raw: "1 500 000 - 2 000 000 FCFA",
  },
  {
    id: "off-2",
    title: "Chef de Projet Digital & Marketing",
    company: "Wave Côte d'Ivoire",
    location: "Abidjan, Plateau",
    filiere: "Marketing & Com",
    source: "Novojob",
    contract_type: "CDI",
    status: "active",
    visible_site: true,
    created_at: "2026-08-22T06:05:00Z",
    source_url: "https://novojob.com/cote-d-ivoire/offre-7890",
    salary_raw: "Négociable",
  },
  {
    id: "off-3",
    title: "Comptable Général Senior",
    company: "Sifca Groupe",
    location: "Abidjan, Treichville",
    filiere: "Comptabilité & Finance",
    source: "Go Africa Online",
    contract_type: "CDI",
    status: "active",
    visible_site: true,
    created_at: "2026-08-21T06:40:00Z",
    source_url: "https://goafricaonline.com/offre-332",
    salary_raw: "800 000 - 1 100 000 FCFA",
  },
  {
    id: "off-4",
    title: "Ingénieur Génie Civil / Conducteur de Travaux",
    company: "PFO Africa",
    location: "Yamoussoukro",
    filiere: "BTP & Génie Civil",
    source: "EmploiDakar CI",
    contract_type: "CDD",
    status: "active",
    visible_site: true,
    created_at: "2026-08-21T06:25:00Z",
    source_url: "https://emploidakar.com/offre-9912",
    salary_raw: "Selon profil",
  },
  {
    id: "off-5",
    title: "Chargé de Recrutement & RH",
    company: "TotalEnergies CI",
    location: "Abidjan, Vridi",
    filiere: "RH",
    source: "LinkedIn",
    contract_type: "CDI",
    status: "expired",
    visible_site: false,
    created_at: "2026-08-10T06:14:00Z",
    source_url: "https://linkedin.com/jobs/view/998877",
    salary_raw: "Confidentiel",
  },
  {
    id: "off-6",
    title: "Data Analyst Junior (Python / SQL)",
    company: "MTN Côte d'Ivoire",
    location: "Abidjan, Marcory",
    filiere: "Tech & Dev",
    source: "Novojob",
    contract_type: "Stage",
    status: "active",
    visible_site: true,
    created_at: "2026-08-22T06:08:00Z",
    source_url: "https://novojob.com/cote-d-ivoire/offre-4411",
    salary_raw: "Indemnité de stage",
  },
]

export const INITIAL_SOURCES = [
  {
    id: "src-1",
    code: "novojob",
    name: "Novojob Côte d'Ivoire",
    base_url: "https://www.novojob.com/cote-d-ivoire/",
    status: "active",
    priority: 1,
    schedule_time: "06:00",
    created_at: "2026-01-10T00:00:00Z",
    total_offers: 1240,
    logo: "/LogoSource/novojob.svg",
  },
  {
    id: "src-2",
    code: "linkedin",
    name: "LinkedIn Jobs CI",
    base_url: "https://www.linkedin.com/jobs/search/?location=Cote%20d'Ivoire",
    status: "active",
    priority: 2,
    schedule_time: "06:15",
    created_at: "2026-01-10T00:00:00Z",
    total_offers: 2890,
    logo: "/LogoSource/linkedin.png",
  },
  {
    id: "src-3",
    code: "emploidakar",
    name: "EmploiDakar CI",
    base_url: "https://www.emploidakar.com/",
    status: "active",
    priority: 3,
    schedule_time: "06:30",
    created_at: "2026-01-10T00:00:00Z",
    total_offers: 830,
    logo: "/LogoSource/emploidakar.svg",
  },
  {
    id: "src-4",
    code: "goafrica",
    name: "Go Africa Online",
    base_url: "https://www.goafricaonline.com/ci/offres-emploi",
    status: "active",
    priority: 4,
    schedule_time: "06:45",
    created_at: "2026-01-10T00:00:00Z",
    total_offers: 1450,
    logo: "/LogoSource/goafrica.svg",
  },
]

export const INITIAL_FILIERES = [
  {
    id: "fil-1",
    slug: "tech-dev",
    label: "Tech & Dev",
    description: "Développement web, mobile, data, DevOps, IA et cybersécurité",
    sort_order: 1,
    is_active: true,
    total_offers: 45,
    specialties: ["Frontend React / Vue", "Backend Python / Node / Java", "DevOps & Cloud", "Data & IA"],
    keywords: [
      { keyword: "react", weight: 90 },
      { keyword: "python", weight: 95 },
      { keyword: "développeur", weight: 100 },
      { keyword: "javascript", weight: 85 },
      { keyword: "fullstack", weight: 90 },
    ],
  },
  {
    id: "fil-2",
    slug: "marketing-com",
    label: "Marketing & Communication",
    description: "Marketing digital, community management, branding et médias",
    sort_order: 2,
    is_active: true,
    total_offers: 32,
    specialties: ["Growth Marketing", "Social Media & Influence", "Brand Management", "Relations Presse"],
    keywords: [
      { keyword: "marketing", weight: 100 },
      { keyword: "community manager", weight: 95 },
      { keyword: "communication", weight: 90 },
      { keyword: "seo", weight: 80 },
    ],
  },
  {
    id: "fil-3",
    slug: "comptabilite-finance",
    label: "Comptabilité & Finance",
    description: "Audit, contrôle de gestion, trésorerie et fiscalité",
    sort_order: 3,
    is_active: true,
    total_offers: 28,
    specialties: ["Comptabilité Générale", "Contrôle de Gestion", "Audit Financier", "Fiscalité"],
    keywords: [
      { keyword: "comptable", weight: 100 },
      { keyword: "audit", weight: 90 },
      { keyword: "finance", weight: 95 },
      { keyword: "trésorier", weight: 85 },
    ],
  },
  {
    id: "fil-4",
    slug: "rh",
    label: "Ressources Humaines",
    description: "Recrutement, gestion des talents, paie et formation",
    sort_order: 4,
    is_active: true,
    total_offers: 21,
    specialties: ["Recrutement & Talent Acquisition", "Administration du personnel", "Gestion de la paie"],
    keywords: [
      { keyword: "rh", weight: 100 },
      { keyword: "recrutement", weight: 95 },
      { keyword: "ressources humaines", weight: 100 },
      { keyword: "gestionnaire paie", weight: 90 },
    ],
  },
  {
    id: "fil-5",
    slug: "btp-genie-civil",
    label: "BTP & Génie Civil",
    description: "Architecture, chantier, conducteur de travaux et topographie",
    sort_order: 5,
    is_active: true,
    total_offers: 19,
    specialties: ["Conduite de Travaux", "Architecture & Dessin BTP", "Topographie", "Bureau d'études"],
    keywords: [
      { keyword: "génie civil", weight: 100 },
      { keyword: "btp", weight: 100 },
      { keyword: "conducteur travaux", weight: 95 },
      { keyword: "chantier", weight: 85 },
    ],
  },
  {
    id: "fil-6",
    slug: "commercial-vente",
    label: "Commercial & Vente",
    description: "Prospection, négociation, grands comptes et retail",
    sort_order: 6,
    is_active: true,
    total_offers: 38,
    specialties: ["Business Developer", "Key Account Manager", "Vente B2B", "Chef de rayon"],
    keywords: [
      { keyword: "commercial", weight: 100 },
      { keyword: "vente", weight: 95 },
      { keyword: "business developer", weight: 90 },
      { keyword: "prospection", weight: 85 },
    ],
  },
]
